



<script src="https://giscus.app/client.js"
        data-repo="michael105/michael105.github.io"
        data-repo-id="R_kgDOOWjZsg"
        data-category="Comments"
        data-category-id="DIC_kwDOOWjZss4Co7O_"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="catppuccin_latte"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>



</div>
</div>
<br><br><br>
<div class="footer">

<div class="bottomright">
<small style="border-top:1px solid black;padding: 3px">
2025  <!--#+e echo `date '+%Y/%m/%d %H:%M'`-->
 misc147 
</small>
</div>


<div class="generation">
<small>
</small>
</div>
</div>

</body>
</html>

