
<style>

body {
		background-color: lightgray;
		background: lightgray;
		font-family: Gentium, "Bitstream Vera Serif", "DejaVu Serif", FreeSerif, Palatino, "Palatino Linotype", "Book Antiqua", serif;
		font-size:0.9em;
}

pre {
		font-size: 1.1em;
		font-weight: 400;
		font-stretch: semi-expanded;
		line-height: 1.5;
		padding-left: 0px;
		//border-left: 1px solid black;
}

.textblock {
		font-size: 1.2em;
		font-weight: 500;
		font-stretch: semi-expanded;
		line-height: 1.4;
		padding-left: 0px;
		//border-left: 1px solid black;
}
.codeblock {
   font-size: 1.1em;
	 color: darkblue;
	 font-weight: 500;
	 border-left: 2px double blue;
	 padding-left: 0px;
	 margin-left: 60px;
}


a {
	color: #990000;
	text-decoration: none;
	border-bottom: 1px solid #990000;
		font-family: Gentium, "Bitstream Vera Serif", "DejaVu Serif", FreeSerif, Palatino, "Palatino Linotype", "Book Antiqua", serif;
}

li {
		margin-bottom: 5px;
		font-family: Gentium, "Bitstream Vera Serif", "DejaVu Serif", FreeSerif, Palatino, "Palatino Linotype", "Book Antiqua", serif;
}

p { 
		text-align: justify;
		margin-top:12px;
}

h2 {
	border-bottom: 2px solid black;
	padding-bottom: 5px;
	margin-bottom: 30px;
	margin-left: -35px;
	//margin-left: -30px;
	margin-right: -40px;
	margin-top: 25px;
}

h4 {
	//border-bottom: 2px solid black;
	margin-top: 40px;
	margin-bottom: 20px;
	margin-left: 4px;
	text-decoration: underline;
}

hr {
		margin: 16px -3px 10px -3px;
}


code {
   font-size: 1.2em;
	 //color: darkblue;
	 color: #04198c;
	 font-weight: 500;
	 border-left: 2px double blue;
	 padding-left: 10px;
}

.header {
		margin: 0px;
		padding: 0px;
		border: 0px;
		position: absolute;
		top: 0px;
		left: 0px;
		right: 0px;
		height: 100px;
		font-size: 12px;
		background: #242424;
		border-bottom: 5px solid #FFB92A;
}

.headline {
		position: relative;
		left: 125px;
		top: 25px;
		text-color: white;
		color: white;
}

.left {
	top: 140px;
	left:0 px;
	width:160px;
	//border-right: 5px solid white;
	position: absolute;
	//padding-top: 20px;
	padding-top: 70px; // evtl
}

.sitediv {
		//height: 100%;
		//top: 0px;
		//left: 170px;
		bottom: 0px;
		position: relative;
		margin: 0px 0px 0px 170px;
		padding: 0px 0px 0px 0px;
}

.content {
	top: 110px;
	padding-top: 2px;
	padding-bottom: 20px;
	//left: 0px;
	width:800px;
	padding-left: 90px;
	//padding-left: 65px;
	padding-right: 50px;
	//padding-right: 25px;
	//padding-left: 35px;
	margin-bottom: 160px;
	position: relative;
		font-family:Gentium,"Bitstream Vera Serif", "DejaVu Serif", FreeSerif,	Palatino, "Palatino Linotype", "Book Antiqua", serif;
		line-height:1.3;
		align=center;

	border-left: 5px solid white;
}

.footer {
		margin: 25px 25px 0px 25px;
		position: relative;
}

.fortune {
		margin: 25px 25px 0px 0px;
		font-size:10pt;
		//right: 40px;
		text-align: right;
		//border-top:1px solid #333333;
		position: relative;
		//bottom:0px;
}


.generation {
		//padding:0px 0px 0px 0px;
		//margin: 25px 25px 0px 25px;
		font-size:10pt;
		//border-top:2px solid #333333;
		position: relative;
		left: 5px;
		top:-8px;
}

section {
		margin: 0px;
}
.heading {
		position: absolute;
		top: 0px;
		left: 0px;
		right: 0px;
		height: 125px;
		font-size: 12px;
		background: #242424;
		border-bottom: 5px solid #FFB92A;
}


</style>




